on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.1

            - name: Setup Node.js
              uses: actions/setup-node@v4.0.2

            - name: Install dependencies
              run: npm install

            - name: 'Create env file'
              run: |
                  touch .env
                  echo VITE_URL_PREFIX=${{ secrets.URL_PREFIX }} >> .env
                  echo VITE_AWS_REGION=${{ secrets.AWS_REGION }} >> .env

                  echo VITE_IMAGE_SERVICE_URL=${{ secrets.IMAGE_SERVICE_URL }} >> .env
                  echo VITE_IMAGE_SERVICE_API_KEY=${{ secrets.IMAGE_SERVICE_API_KEY }} >> .env

                  echo VITE_RECIPES_SERVICE_URL=${{ secrets.RECIPES_SERVICE_URL }} >> .env
                  echo VITE_RECIPES_IDENTITY_POOL_ID=${{ secrets.RECIPES_IDENTITY_POOL_ID }} >> .env

            - name: Build
              run: npm run build

            - name: Archive dist directory
              uses: actions/upload-artifact@v4.3.1
              with:
                  name: dist
                  path: dist

    #   test:
    #     runs-on: ubuntu-latest
    #     needs: build
    #     steps:
    #       - uses: actions/checkout@v4.1.1

    #       - name: Setup Node.js
    #         uses: actions/setup-node@v4.0.2

    #       - name: Install dependencies for testing
    #         run: npm install

    #       - name: Run Tests
    #         run: npm run test

    deploy:
        runs-on: ubuntu-latest
        # needs: [test, build]
        needs: [build]
        env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            SOURCE_DIR: 'dist'
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4.1.2
              with:
                  name: dist
                  path: dist

            - name: Remove top-level index.html
              run: aws s3 rm s3://$AWS_S3_BUCKET/index.html

            - name: Upload new index.html
              run: aws s3 cp dist/index.html s3://$AWS_S3_BUCKET/

            - name: Delete old JS and CSS files
              run: |
                  aws s3 rm s3://$AWS_S3_BUCKET/assets/ --recursive \
                  --exclude "*" \
                  --include "*.js" \
                  --include "*.css"

            - name: Upload new JS and CSS
              run: |
                  aws s3 cp dist/assets/ s3://$AWS_S3_BUCKET/assets/ --recursive \
                  --exclude "*" \
                  --include "*.js" \
                  --include "*.css"

            - name: Invalidate CloudFront
              uses: chetan/invalidate-cloudfront-action@v2
              env:
                  DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION }}
                  PATHS: '/*'
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
